In [22]:
import requests
import pandas as pd

In [23]:
url = "https://dummyjson.com/carts"

In [24]:
data = requests.get(url)
data.status_code

200

In [25]:
cart = data.json()
cart

{'carts': [{'id': 1,
   'products': [{'id': 162,
     'title': 'Blue Frock',
     'price': 29.99,
     'quantity': 4,
     'total': 119.96,
     'discountPercentage': 12.13,
     'discountedTotal': 105.41,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/tops/blue-frock/thumbnail.webp'},
    {'id': 113,
     'title': 'Generic Motorcycle',
     'price': 3999.99,
     'quantity': 3,
     'total': 11999.97,
     'discountPercentage': 12.1,
     'discountedTotal': 10547.97,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/motorcycle/generic-motorcycle/thumbnail.webp'},
    {'id': 122,
     'title': 'iPhone 6',
     'price': 299.99,
     'quantity': 3,
     'total': 899.97,
     'discountPercentage': 6.69,
     'discountedTotal': 839.76,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/iphone-6/thumbnail.webp'},
    {'id': 138,
     'title': 'Baseball Ball',
     'price': 8.99,
     'quantity': 2,
     'total': 17.98,
     'discountPercentage': 1.71,
     'discountedTotal': 17.67,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/sports-accessories/baseball-ball/thumbnail.webp'}],
   'total': 13037.88,
   'discountedTotal': 11510.81,
   'userId': 1,
   'totalProducts': 4,
   'totalQuantity': 12},
  {'id': 2,
   'products': [{'id': 86,
     'title': 'Man Short Sleeve Shirt',
     'price': 19.99,
     'quantity': 5,
     'total': 99.94999999999999,
     'discountPercentage': 6.83,
     'discountedTotal': 93.12,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/thumbnail.webp'},
    {'id': 104,
     'title': 'Apple iPhone Charger',
     'price': 19.99,
     'quantity': 2,
     'total': 39.98,
     'discountPercentage': 18.52,
     'discountedTotal': 32.58,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/thumbnail.webp'}],
   'total': 139.93,
   'discountedTotal': 125.7,
   'userId': 2,
   'totalProducts': 2,
   'totalQuantity': 7},
  {'id': 3,
   'products': [{'id': 24,
     'title': 'Fish Steak',
     'price': 14.99,
     'quantity': 1,
     'total': 14.99,
     'discountPercentage': 4.23,
     'discountedTotal': 14.36,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/fish-steak/thumbnail.webp'},
    {'id': 123,
     'title': 'iPhone 13 Pro',
     'price': 1099.99,
     'quantity': 1,
     'total': 1099.99,
     'discountPercentage': 9.37,
     'discountedTotal': 996.92,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/thumbnail.webp'},
    {'id': 129,
     'title': 'Realme X',
     'price': 299.99,
     'quantity': 1,
     'total': 299.99,
     'discountPercentage': 6.95,
     'discountedTotal': 279.14,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/realme-x/thumbnail.webp'},
    {'id': 86,
     'title': 'Man Short Sleeve Shirt',
     'price': 19.99,
     'quantity': 5,
     'total': 99.94999999999999,
     'discountPercentage': 6.83,
     'discountedTotal': 93.12,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/thumbnail.webp'},
    {'id': 8,
     'title': "Dior J'adore",
     'price': 89.99,
     'quantity': 2,
     'total': 179.98,
     'discountPercentage': 14.72,
     'discountedTotal': 153.49,
     'thumbnail': "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"},
    {'id': 157,
     'title': 'Party Glasses',
     'price': 19.99,
     'quantity': 5,
     'total': 99.94999999999999,
     'discountPercentage': 11.22,
     'discountedTotal': 88.74,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/sunglasses/party-glasses/thumbnail.webp'}],
   'total': 1794.85,
   'discountedTotal': 1625.77,
   'userId': 3,
   'totalProducts': 6,
   'totalQuantity': 15},
  {'id': 4,
   'products': [{'id': 92,
     'title': 'Sports Sneakers Off White Red',
     'price': 109.99,
     'quantity': 3,
     'total': 329.96999999999997,
     'discountPercentage': 0.04,
     'discountedTotal': 329.84,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/thumbnail.webp'},
    {'id': 8,
     'title': "Dior J'adore",
     'price': 89.99,
     'quantity': 4,
     'total': 359.96,
     'discountPercentage': 14.72,
     'discountedTotal': 306.97,
     'thumbnail': "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"}],
   'total': 689.93,
   'discountedTotal': 636.81,
   'userId': 4,
   'totalProducts': 2,
   'totalQuantity': 7},
  {'id': 5,
   'products': [{'id': 161,
     'title': 'Samsung Galaxy Tab White',
     'price': 349.99,
     'quantity': 4,
     'total': 1399.96,
     'discountPercentage': 18.2,
     'discountedTotal': 1145.17,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/thumbnail.webp'},
    {'id': 39,
     'title': 'Soft Drinks',
     'price': 1.99,
     'quantity': 4,
     'total': 7.96,
     'discountPercentage': 17.48,
     'discountedTotal': 6.57,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/soft-drinks/thumbnail.webp'},
    {'id': 3,
     'title': 'Powder Canister',
     'price': 14.99,
     'quantity': 4,
     'total': 59.96,
     'discountPercentage': 9.84,
     'discountedTotal': 54.06,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp'}],
   'total': 1467.88,
   'discountedTotal': 1205.8,
   'userId': 5,
   'totalProducts': 3,
   'totalQuantity': 12},
  {'id': 6,
   'products': [{'id': 192,
     'title': 'Rolex Datejust Women',
     'price': 10999.99,
     'quantity': 5,
     'total': 54999.95,
     'discountPercentage': 15.94,
     'discountedTotal': 46232.96,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/womens-watches/rolex-datejust-women/thumbnail.webp'},
    {'id': 130,
     'title': 'Realme XT',
     'price': 349.99,
     'quantity': 1,
     'total': 349.99,
     'discountPercentage': 11.51,
     'discountedTotal': 309.71,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/realme-xt/thumbnail.webp'},
    {'id': 155,
     'title': 'Classic Sun Glasses',
     'price': 24.99,
     'quantity': 4,
     'total': 99.96,
     'discountPercentage': 4.94,
     'discountedTotal': 95.02,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/sunglasses/classic-sun-glasses/thumbnail.webp'},
    {'id': 42,
     'title': 'Water',
     'price': 0.99,
     'quantity': 4,
     'total': 3.96,
     'discountPercentage': 14.92,
     'discountedTotal': 3.37,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/water/thumbnail.webp'}],
   'total': 55453.86,
   'discountedTotal': 46641.06,
   'userId': 6,
   'totalProducts': 4,
   'totalQuantity': 14},
  {'id': 7,
   'products': [{'id': 56,
     'title': 'Electric Stove',
     'price': 49.99,
     'quantity': 1,
     'total': 49.99,
     'discountPercentage': 14.04,
     'discountedTotal': 42.97,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/electric-stove/thumbnail.webp'},
    {'id': 136,
     'title': 'Vivo X21',
     'price': 499.99,
     'quantity': 1,
     'total': 499.99,
     'discountPercentage': 17.41,
     'discountedTotal': 412.94,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/vivo-x21/thumbnail.webp'},
    {'id': 9,
     'title': 'Dolce Shine Eau de',
     'price': 69.99,
     'quantity': 2,
     'total': 139.98,
     'discountPercentage': 0.62,
     'discountedTotal': 139.11,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp'},
    {'id': 120,
     'title': 'Vaseline Men Body and Face Lotion',
     'price': 9.99,
     'quantity': 4,
     'total': 39.96,
     'discountPercentage': 13.39,
     'discountedTotal': 34.61,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/skin-care/vaseline-men-body-and-face-lotion/thumbnail.webp'},
    {'id': 56,
     'title': 'Electric Stove',
     'price': 49.99,
     'quantity': 1,
     'total': 49.99,
     'discountPercentage': 14.04,
     'discountedTotal': 42.97,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/electric-stove/thumbnail.webp'},
    {'id': 90,
     'title': 'Puma Future Rider Trainers',
     'price': 89.99,
     'quantity': 5,
     'total': 449.95,
     'discountPercentage': 4.2,
     'discountedTotal': 431.05,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/thumbnail.webp'}],
   'total': 1229.86,
   'discountedTotal': 1103.65,
   'userId': 7,
   'totalProducts': 6,
   'totalQuantity': 14},
  {'id': 8,
   'products': [{'id': 18,
     'title': 'Cat Food',
     'price': 8.99,
     'quantity': 2,
     'total': 17.98,
     'discountPercentage': 9.58,
     'discountedTotal': 16.26,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/cat-food/thumbnail.webp'},
    {'id': 50,
     'title': 'Black Whisk',
     'price': 9.99,
     'quantity': 3,
     'total': 29.97,
     'discountPercentage': 10.24,
     'discountedTotal': 26.9,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/black-whisk/thumbnail.webp'},
    {'id': 162,
     'title': 'Blue Frock',
     'price': 29.99,
     'quantity': 4,
     'total': 119.96,
     'discountPercentage': 12.13,
     'discountedTotal': 105.41,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/tops/blue-frock/thumbnail.webp'},
    {'id': 11,
     'title': 'Annibale Colombo Bed',
     'price': 1899.99,
     'quantity': 3,
     'total': 5699.97,
     'discountPercentage': 8.57,
     'discountedTotal': 5211.48,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp'},
    {'id': 108,
     'title': 'iPhone 12 Silicone Case with MagSafe Plum',
     'price': 29.99,
     'quantity': 4,
     'total': 119.96,
     'discountPercentage': 13.85,
     'discountedTotal': 103.35,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/thumbnail.webp'},
    {'id': 106,
     'title': 'Apple Watch Series 4 Gold',
     'price': 349.99,
     'quantity': 1,
     'total': 349.99,
     'discountPercentage': 12.02,
     'discountedTotal': 307.92,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-watch-series-4-gold/thumbnail.webp'}],
   'total': 6337.83,
   'discountedTotal': 5771.32,
   'userId': 8,
   'totalProducts': 6,
   'totalQuantity': 17},
  {'id': 9,
   'products': [{'id': 1,
     'title': 'Essence Mascara Lash Princess',
     'price': 9.99,
     'quantity': 3,
     'total': 29.97,
     'discountPercentage': 10.48,
     'discountedTotal': 26.83,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp'},
    {'id': 98,
     'title': 'Rolex Submariner Watch',
     'price': 13999.99,
     'quantity': 2,
     'total': 27999.98,
     'discountPercentage': 5.05,
     'discountedTotal': 26585.98,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-watches/rolex-submariner-watch/thumbnail.webp'},
    {'id': 132,
     'title': 'Samsung Galaxy S8',
     'price': 499.99,
     'quantity': 3,
     'total': 1499.97,
     'discountPercentage': 19.45,
     'discountedTotal': 1208.23,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s8/thumbnail.webp'},
    {'id': 90,
     'title': 'Puma Future Rider Trainers',
     'price': 89.99,
     'quantity': 2,
     'total': 179.98,
     'discountPercentage': 4.2,
     'discountedTotal': 172.42,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/thumbnail.webp'}],
   'total': 29709.9,
   'discountedTotal': 27993.46,
   'userId': 9,
   'totalProducts': 4,
   'totalQuantity': 10},
  {'id': 10,
   'products': [{'id': 41,
     'title': 'Tissue Paper Box',
     'price': 2.49,
     'quantity': 1,
     'total': 2.49,
     'discountPercentage': 13.28,
     'discountedTotal': 2.16,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/tissue-paper-box/thumbnail.webp'},
    {'id': 108,
     'title': 'iPhone 12 Silicone Case with MagSafe Plum',
     'price': 29.99,
     'quantity': 5,
     'total': 149.95,
     'discountPercentage': 13.85,
     'discountedTotal': 129.18,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/thumbnail.webp'}],
   'total': 152.44,
   'discountedTotal': 131.34,
   'userId': 10,
   'totalProducts': 2,
   'totalQuantity': 6},
  {'id': 11,
   'products': [{'id': 115,
     'title': 'MotoGP CI.H1',
     'price': 14999.99,
     'quantity': 4,
     'total': 59999.96,
     'discountPercentage': 6.92,
     'discountedTotal': 55847.96,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/motorcycle/motogp-ci.h1/thumbnail.webp'},
    {'id': 101,
     'title': 'Apple AirPods Max Silver',
     'price': 549.99,
     'quantity': 2,
     'total': 1099.98,
     'discountPercentage': 13.67,
     'discountedTotal': 949.61,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/thumbnail.webp'},
    {'id': 55,
     'title': 'Egg Slicer',
     'price': 6.99,
     'quantity': 4,
     'total': 27.96,
     'discountPercentage': 14.76,
     'discountedTotal': 23.83,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/egg-slicer/thumbnail.webp'},
    {'id': 25,
     'title': 'Green Bell Pepper',
     'price': 1.29,
     'quantity': 3,
     'total': 3.87,
     'discountPercentage': 0.16,
     'discountedTotal': 3.86,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/thumbnail.webp'},
    {'id': 161,
     'title': 'Samsung Galaxy Tab White',
     'price': 349.99,
     'quantity': 2,
     'total': 699.98,
     'discountPercentage': 18.2,
     'discountedTotal': 572.58,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/thumbnail.webp'}],
   'total': 61831.75,
   'discountedTotal': 57397.84,
   'userId': 11,
   'totalProducts': 5,
   'totalQuantity': 15},
  {'id': 12,
   'products': [{'id': 117,
     'title': 'Sportbike Motorcycle',
     'price': 7499.99,
     'quantity': 1,
     'total': 7499.99,
     'discountPercentage': 11.58,
     'discountedTotal': 6631.49,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/motorcycle/sportbike-motorcycle/thumbnail.webp'},
    {'id': 28,
     'title': 'Ice Cream',
     'price': 5.49,
     'quantity': 5,
     'total': 27.450000000000003,
     'discountPercentage': 8.69,
     'discountedTotal': 25.06,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/ice-cream/thumbnail.webp'},
    {'id': 98,
     'title': 'Rolex Submariner Watch',
     'price': 13999.99,
     'quantity': 2,
     'total': 27999.98,
     'discountPercentage': 5.05,
     'discountedTotal': 26585.98,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-watches/rolex-submariner-watch/thumbnail.webp'},
    {'id': 8,
     'title': "Dior J'adore",
     'price': 89.99,
     'quantity': 1,
     'total': 89.99,
     'discountPercentage': 14.72,
     'discountedTotal': 76.74,
     'thumbnail': "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"},
    {'id': 162,
     'title': 'Blue Frock',
     'price': 29.99,
     'quantity': 5,
     'total': 149.95,
     'discountPercentage': 12.13,
     'discountedTotal': 131.76,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/tops/blue-frock/thumbnail.webp'},
    {'id': 14,
     'title': 'Knoll Saarinen Executive Conference Chair',
     'price': 499.99,
     'quantity': 4,
     'total': 1999.96,
     'discountPercentage': 2.01,
     'discountedTotal': 1959.76,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/thumbnail.webp'}],
   'total': 37767.32,
   'discountedTotal': 35410.79,
   'userId': 12,
   'totalProducts': 6,
   'totalQuantity': 18},
  {'id': 13,
   'products': [{'id': 35,
     'title': 'Potatoes',
     'price': 2.29,
     'quantity': 2,
     'total': 4.58,
     'discountPercentage': 5.38,
     'discountedTotal': 4.33,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/potatoes/thumbnail.webp'},
    {'id': 23,
     'title': 'Eggs',
     'price': 2.99,
     'quantity': 4,
     'total': 11.96,
     'discountPercentage': 11.05,
     'discountedTotal': 10.64,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/eggs/thumbnail.webp'}],
   'total': 16.54,
   'discountedTotal': 14.97,
   'userId': 13,
   'totalProducts': 2,
   'totalQuantity': 6},
  {'id': 14,
   'products': [{'id': 44,
     'title': 'Family Tree Photo Frame',
     'price': 29.99,
     'quantity': 4,
     'total': 119.96,
     'discountPercentage': 14.87,
     'discountedTotal': 102.12,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/home-decoration/family-tree-photo-frame/thumbnail.webp'},
    {'id': 68,
     'title': 'Pan',
     'price': 24.99,
     'quantity': 1,
     'total': 24.99,
     'discountPercentage': 3,
     'discountedTotal': 24.24,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/pan/thumbnail.webp'},
    {'id': 65,
     'title': 'Lunch Box',
     'price': 12.99,
     'quantity': 5,
     'total': 64.95,
     'discountPercentage': 10.34,
     'discountedTotal': 58.23,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/lunch-box/thumbnail.webp'}],
   'total': 209.9,
   'discountedTotal': 184.59,
   'userId': 14,
   'totalProducts': 3,
   'totalQuantity': 10},
  {'id': 15,
   'products': [{'id': 61,
     'title': 'Hand Blender',
     'price': 34.99,
     'quantity': 2,
     'total': 69.98,
     'discountPercentage': 17.02,
     'discountedTotal': 58.07,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/hand-blender/thumbnail.webp'},
    {'id': 105,
     'title': 'Apple MagSafe Battery Pack',
     'price': 99.99,
     'quantity': 1,
     'total': 99.99,
     'discountPercentage': 17.17,
     'discountedTotal': 82.82,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/thumbnail.webp'},
    {'id': 141,
     'title': 'Basketball Rim',
     'price': 39.99,
     'quantity': 2,
     'total': 79.98,
     'discountPercentage': 7.74,
     'discountedTotal': 73.79,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/sports-accessories/basketball-rim/thumbnail.webp'}],
   'total': 249.95,
   'discountedTotal': 214.68,
   'userId': 15,
   'totalProducts': 3,
   'totalQuantity': 5},
  {'id': 16,
   'products': [{'id': 20,
     'title': 'Cooking Oil',
     'price': 4.99,
     'quantity': 5,
     'total': 24.950000000000003,
     'discountPercentage': 9.33,
     'discountedTotal': 22.62,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/cooking-oil/thumbnail.webp'},
    {'id': 91,
     'title': 'Sports Sneakers Off White & Red',
     'price': 119.99,
     'quantity': 3,
     'total': 359.96999999999997,
     'discountPercentage': 4.97,
     'discountedTotal': 342.08,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/thumbnail.webp'}],
   'total': 384.92,
   'discountedTotal': 364.7,
   'userId': 16,
   'totalProducts': 2,
   'totalQuantity': 8},
  {'id': 17,
   'products': [{'id': 123,
     'title': 'iPhone 13 Pro',
     'price': 1099.99,
     'quantity': 5,
     'total': 5499.95,
     'discountPercentage': 9.37,
     'discountedTotal': 4984.6,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/thumbnail.webp'},
    {'id': 137,
     'title': 'American Football',
     'price': 19.99,

In [26]:
type (cart)

dict

In [28]:
cart_data = cart["carts"]
cart_data

[{'id': 1,
  'products': [{'id': 162,
    'title': 'Blue Frock',
    'price': 29.99,
    'quantity': 4,
    'total': 119.96,
    'discountPercentage': 12.13,
    'discountedTotal': 105.41,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/tops/blue-frock/thumbnail.webp'},
   {'id': 113,
    'title': 'Generic Motorcycle',
    'price': 3999.99,
    'quantity': 3,
    'total': 11999.97,
    'discountPercentage': 12.1,
    'discountedTotal': 10547.97,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/motorcycle/generic-motorcycle/thumbnail.webp'},
   {'id': 122,
    'title': 'iPhone 6',
    'price': 299.99,
    'quantity': 3,
    'total': 899.97,
    'discountPercentage': 6.69,
    'discountedTotal': 839.76,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/iphone-6/thumbnail.webp'},
   {'id': 138,
    'title': 'Baseball Ball',
    'price': 8.99,
    'quantity': 2,
    'total': 17.98,
    'discountPercentage': 1.71,
    'discountedTotal': 17.67,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/sports-accessories/baseball-ball/thumbnail.webp'}],
  'total': 13037.88,
  'discountedTotal': 11510.81,
  'userId': 1,
  'totalProducts': 4,
  'totalQuantity': 12},
 {'id': 2,
  'products': [{'id': 86,
    'title': 'Man Short Sleeve Shirt',
    'price': 19.99,
    'quantity': 5,
    'total': 99.94999999999999,
    'discountPercentage': 6.83,
    'discountedTotal': 93.12,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/thumbnail.webp'},
   {'id': 104,
    'title': 'Apple iPhone Charger',
    'price': 19.99,
    'quantity': 2,
    'total': 39.98,
    'discountPercentage': 18.52,
    'discountedTotal': 32.58,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/thumbnail.webp'}],
  'total': 139.93,
  'discountedTotal': 125.7,
  'userId': 2,
  'totalProducts': 2,
  'totalQuantity': 7},
 {'id': 3,
  'products': [{'id': 24,
    'title': 'Fish Steak',
    'price': 14.99,
    'quantity': 1,
    'total': 14.99,
    'discountPercentage': 4.23,
    'discountedTotal': 14.36,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/fish-steak/thumbnail.webp'},
   {'id': 123,
    'title': 'iPhone 13 Pro',
    'price': 1099.99,
    'quantity': 1,
    'total': 1099.99,
    'discountPercentage': 9.37,
    'discountedTotal': 996.92,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/thumbnail.webp'},
   {'id': 129,
    'title': 'Realme X',
    'price': 299.99,
    'quantity': 1,
    'total': 299.99,
    'discountPercentage': 6.95,
    'discountedTotal': 279.14,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/realme-x/thumbnail.webp'},
   {'id': 86,
    'title': 'Man Short Sleeve Shirt',
    'price': 19.99,
    'quantity': 5,
    'total': 99.94999999999999,
    'discountPercentage': 6.83,
    'discountedTotal': 93.12,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/thumbnail.webp'},
   {'id': 8,
    'title': "Dior J'adore",
    'price': 89.99,
    'quantity': 2,
    'total': 179.98,
    'discountPercentage': 14.72,
    'discountedTotal': 153.49,
    'thumbnail': "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"},
   {'id': 157,
    'title': 'Party Glasses',
    'price': 19.99,
    'quantity': 5,
    'total': 99.94999999999999,
    'discountPercentage': 11.22,
    'discountedTotal': 88.74,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/sunglasses/party-glasses/thumbnail.webp'}],
  'total': 1794.85,
  'discountedTotal': 1625.77,
  'userId': 3,
  'totalProducts': 6,
  'totalQuantity': 15},
 {'id': 4,
  'products': [{'id': 92,
    'title': 'Sports Sneakers Off White Red',
    'price': 109.99,
    'quantity': 3,
    'total': 329.96999999999997,
    'discountPercentage': 0.04,
    'discountedTotal': 329.84,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/thumbnail.webp'},
   {'id': 8,
    'title': "Dior J'adore",
    'price': 89.99,
    'quantity': 4,
    'total': 359.96,
    'discountPercentage': 14.72,
    'discountedTotal': 306.97,
    'thumbnail': "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"}],
  'total': 689.93,
  'discountedTotal': 636.81,
  'userId': 4,
  'totalProducts': 2,
  'totalQuantity': 7},
 {'id': 5,
  'products': [{'id': 161,
    'title': 'Samsung Galaxy Tab White',
    'price': 349.99,
    'quantity': 4,
    'total': 1399.96,
    'discountPercentage': 18.2,
    'discountedTotal': 1145.17,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/thumbnail.webp'},
   {'id': 39,
    'title': 'Soft Drinks',
    'price': 1.99,
    'quantity': 4,
    'total': 7.96,
    'discountPercentage': 17.48,
    'discountedTotal': 6.57,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/soft-drinks/thumbnail.webp'},
   {'id': 3,
    'title': 'Powder Canister',
    'price': 14.99,
    'quantity': 4,
    'total': 59.96,
    'discountPercentage': 9.84,
    'discountedTotal': 54.06,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp'}],
  'total': 1467.88,
  'discountedTotal': 1205.8,
  'userId': 5,
  'totalProducts': 3,
  'totalQuantity': 12},
 {'id': 6,
  'products': [{'id': 192,
    'title': 'Rolex Datejust Women',
    'price': 10999.99,
    'quantity': 5,
    'total': 54999.95,
    'discountPercentage': 15.94,
    'discountedTotal': 46232.96,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/womens-watches/rolex-datejust-women/thumbnail.webp'},
   {'id': 130,
    'title': 'Realme XT',
    'price': 349.99,
    'quantity': 1,
    'total': 349.99,
    'discountPercentage': 11.51,
    'discountedTotal': 309.71,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/realme-xt/thumbnail.webp'},
   {'id': 155,
    'title': 'Classic Sun Glasses',
    'price': 24.99,
    'quantity': 4,
    'total': 99.96,
    'discountPercentage': 4.94,
    'discountedTotal': 95.02,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/sunglasses/classic-sun-glasses/thumbnail.webp'},
   {'id': 42,
    'title': 'Water',
    'price': 0.99,
    'quantity': 4,
    'total': 3.96,
    'discountPercentage': 14.92,
    'discountedTotal': 3.37,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/water/thumbnail.webp'}],
  'total': 55453.86,
  'discountedTotal': 46641.06,
  'userId': 6,
  'totalProducts': 4,
  'totalQuantity': 14},
 {'id': 7,
  'products': [{'id': 56,
    'title': 'Electric Stove',
    'price': 49.99,
    'quantity': 1,
    'total': 49.99,
    'discountPercentage': 14.04,
    'discountedTotal': 42.97,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/electric-stove/thumbnail.webp'},
   {'id': 136,
    'title': 'Vivo X21',
    'price': 499.99,
    'quantity': 1,
    'total': 499.99,
    'discountPercentage': 17.41,
    'discountedTotal': 412.94,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/vivo-x21/thumbnail.webp'},
   {'id': 9,
    'title': 'Dolce Shine Eau de',
    'price': 69.99,
    'quantity': 2,
    'total': 139.98,
    'discountPercentage': 0.62,
    'discountedTotal': 139.11,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp'},
   {'id': 120,
    'title': 'Vaseline Men Body and Face Lotion',
    'price': 9.99,
    'quantity': 4,
    'total': 39.96,
    'discountPercentage': 13.39,
    'discountedTotal': 34.61,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/skin-care/vaseline-men-body-and-face-lotion/thumbnail.webp'},
   {'id': 56,
    'title': 'Electric Stove',
    'price': 49.99,
    'quantity': 1,
    'total': 49.99,
    'discountPercentage': 14.04,
    'discountedTotal': 42.97,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/electric-stove/thumbnail.webp'},
   {'id': 90,
    'title': 'Puma Future Rider Trainers',
    'price': 89.99,
    'quantity': 5,
    'total': 449.95,
    'discountPercentage': 4.2,
    'discountedTotal': 431.05,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/thumbnail.webp'}],
  'total': 1229.86,
  'discountedTotal': 1103.65,
  'userId': 7,
  'totalProducts': 6,
  'totalQuantity': 14},
 {'id': 8,
  'products': [{'id': 18,
    'title': 'Cat Food',
    'price': 8.99,
    'quantity': 2,
    'total': 17.98,
    'discountPercentage': 9.58,
    'discountedTotal': 16.26,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/cat-food/thumbnail.webp'},
   {'id': 50,
    'title': 'Black Whisk',
    'price': 9.99,
    'quantity': 3,
    'total': 29.97,
    'discountPercentage': 10.24,
    'discountedTotal': 26.9,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/black-whisk/thumbnail.webp'},
   {'id': 162,
    'title': 'Blue Frock',
    'price': 29.99,
    'quantity': 4,
    'total': 119.96,
    'discountPercentage': 12.13,
    'discountedTotal': 105.41,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/tops/blue-frock/thumbnail.webp'},
   {'id': 11,
    'title': 'Annibale Colombo Bed',
    'price': 1899.99,
    'quantity': 3,
    'total': 5699.97,
    'discountPercentage': 8.57,
    'discountedTotal': 5211.48,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp'},
   {'id': 108,
    'title': 'iPhone 12 Silicone Case with MagSafe Plum',
    'price': 29.99,
    'quantity': 4,
    'total': 119.96,
    'discountPercentage': 13.85,
    'discountedTotal': 103.35,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/thumbnail.webp'},
   {'id': 106,
    'title': 'Apple Watch Series 4 Gold',
    'price': 349.99,
    'quantity': 1,
    'total': 349.99,
    'discountPercentage': 12.02,
    'discountedTotal': 307.92,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-watch-series-4-gold/thumbnail.webp'}],
  'total': 6337.83,
  'discountedTotal': 5771.32,
  'userId': 8,
  'totalProducts': 6,
  'totalQuantity': 17},
 {'id': 9,
  'products': [{'id': 1,
    'title': 'Essence Mascara Lash Princess',
    'price': 9.99,
    'quantity': 3,
    'total': 29.97,
    'discountPercentage': 10.48,
    'discountedTotal': 26.83,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp'},
   {'id': 98,
    'title': 'Rolex Submariner Watch',
    'price': 13999.99,
    'quantity': 2,
    'total': 27999.98,
    'discountPercentage': 5.05,
    'discountedTotal': 26585.98,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-watches/rolex-submariner-watch/thumbnail.webp'},
   {'id': 132,
    'title': 'Samsung Galaxy S8',
    'price': 499.99,
    'quantity': 3,
    'total': 1499.97,
    'discountPercentage': 19.45,
    'discountedTotal': 1208.23,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s8/thumbnail.webp'},
   {'id': 90,
    'title': 'Puma Future Rider Trainers',
    'price': 89.99,
    'quantity': 2,
    'total': 179.98,
    'discountPercentage': 4.2,
    'discountedTotal': 172.42,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/thumbnail.webp'}],
  'total': 29709.9,
  'discountedTotal': 27993.46,
  'userId': 9,
  'totalProducts': 4,
  'totalQuantity': 10},
 {'id': 10,
  'products': [{'id': 41,
    'title': 'Tissue Paper Box',
    'price': 2.49,
    'quantity': 1,
    'total': 2.49,
    'discountPercentage': 13.28,
    'discountedTotal': 2.16,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/tissue-paper-box/thumbnail.webp'},
   {'id': 108,
    'title': 'iPhone 12 Silicone Case with MagSafe Plum',
    'price': 29.99,
    'quantity': 5,
    'total': 149.95,
    'discountPercentage': 13.85,
    'discountedTotal': 129.18,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/thumbnail.webp'}],
  'total': 152.44,
  'discountedTotal': 131.34,
  'userId': 10,
  'totalProducts': 2,
  'totalQuantity': 6},
 {'id': 11,
  'products': [{'id': 115,
    'title': 'MotoGP CI.H1',
    'price': 14999.99,
    'quantity': 4,
    'total': 59999.96,
    'discountPercentage': 6.92,
    'discountedTotal': 55847.96,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/motorcycle/motogp-ci.h1/thumbnail.webp'},
   {'id': 101,
    'title': 'Apple AirPods Max Silver',
    'price': 549.99,
    'quantity': 2,
    'total': 1099.98,
    'discountPercentage': 13.67,
    'discountedTotal': 949.61,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/thumbnail.webp'},
   {'id': 55,
    'title': 'Egg Slicer',
    'price': 6.99,
    'quantity': 4,
    'total': 27.96,
    'discountPercentage': 14.76,
    'discountedTotal': 23.83,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/egg-slicer/thumbnail.webp'},
   {'id': 25,
    'title': 'Green Bell Pepper',
    'price': 1.29,
    'quantity': 3,
    'total': 3.87,
    'discountPercentage': 0.16,
    'discountedTotal': 3.86,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/thumbnail.webp'},
   {'id': 161,
    'title': 'Samsung Galaxy Tab White',
    'price': 349.99,
    'quantity': 2,
    'total': 699.98,
    'discountPercentage': 18.2,
    'discountedTotal': 572.58,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/thumbnail.webp'}],
  'total': 61831.75,
  'discountedTotal': 57397.84,
  'userId': 11,
  'totalProducts': 5,
  'totalQuantity': 15},
 {'id': 12,
  'products': [{'id': 117,
    'title': 'Sportbike Motorcycle',
    'price': 7499.99,
    'quantity': 1,
    'total': 7499.99,
    'discountPercentage': 11.58,
    'discountedTotal': 6631.49,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/motorcycle/sportbike-motorcycle/thumbnail.webp'},
   {'id': 28,
    'title': 'Ice Cream',
    'price': 5.49,
    'quantity': 5,
    'total': 27.450000000000003,
    'discountPercentage': 8.69,
    'discountedTotal': 25.06,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/ice-cream/thumbnail.webp'},
   {'id': 98,
    'title': 'Rolex Submariner Watch',
    'price': 13999.99,
    'quantity': 2,
    'total': 27999.98,
    'discountPercentage': 5.05,
    'discountedTotal': 26585.98,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-watches/rolex-submariner-watch/thumbnail.webp'},
   {'id': 8,
    'title': "Dior J'adore",
    'price': 89.99,
    'quantity': 1,
    'total': 89.99,
    'discountPercentage': 14.72,
    'discountedTotal': 76.74,
    'thumbnail': "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"},
   {'id': 162,
    'title': 'Blue Frock',
    'price': 29.99,
    'quantity': 5,
    'total': 149.95,
    'discountPercentage': 12.13,
    'discountedTotal': 131.76,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/tops/blue-frock/thumbnail.webp'},
   {'id': 14,
    'title': 'Knoll Saarinen Executive Conference Chair',
    'price': 499.99,
    'quantity': 4,
    'total': 1999.96,
    'discountPercentage': 2.01,
    'discountedTotal': 1959.76,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/thumbnail.webp'}],
  'total': 37767.32,
  'discountedTotal': 35410.79,
  'userId': 12,
  'totalProducts': 6,
  'totalQuantity': 18},
 {'id': 13,
  'products': [{'id': 35,
    'title': 'Potatoes',
    'price': 2.29,
    'quantity': 2,
    'total': 4.58,
    'discountPercentage': 5.38,
    'discountedTotal': 4.33,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/potatoes/thumbnail.webp'},
   {'id': 23,
    'title': 'Eggs',
    'price': 2.99,
    'quantity': 4,
    'total': 11.96,
    'discountPercentage': 11.05,
    'discountedTotal': 10.64,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/eggs/thumbnail.webp'}],
  'total': 16.54,
  'discountedTotal': 14.97,
  'userId': 13,
  'totalProducts': 2,
  'totalQuantity': 6},
 {'id': 14,
  'products': [{'id': 44,
    'title': 'Family Tree Photo Frame',
    'price': 29.99,
    'quantity': 4,
    'total': 119.96,
    'discountPercentage': 14.87,
    'discountedTotal': 102.12,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/home-decoration/family-tree-photo-frame/thumbnail.webp'},
   {'id': 68,
    'title': 'Pan',
    'price': 24.99,
    'quantity': 1,
    'total': 24.99,
    'discountPercentage': 3,
    'discountedTotal': 24.24,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/pan/thumbnail.webp'},
   {'id': 65,
    'title': 'Lunch Box',
    'price': 12.99,
    'quantity': 5,
    'total': 64.95,
    'discountPercentage': 10.34,
    'discountedTotal': 58.23,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/lunch-box/thumbnail.webp'}],
  'total': 209.9,
  'discountedTotal': 184.59,
  'userId': 14,
  'totalProducts': 3,
  'totalQuantity': 10},
 {'id': 15,
  'products': [{'id': 61,
    'title': 'Hand Blender',
    'price': 34.99,
    'quantity': 2,
    'total': 69.98,
    'discountPercentage': 17.02,
    'discountedTotal': 58.07,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/hand-blender/thumbnail.webp'},
   {'id': 105,
    'title': 'Apple MagSafe Battery Pack',
    'price': 99.99,
    'quantity': 1,
    'total': 99.99,
    'discountPercentage': 17.17,
    'discountedTotal': 82.82,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/thumbnail.webp'},
   {'id': 141,
    'title': 'Basketball Rim',
    'price': 39.99,
    'quantity': 2,
    'total': 79.98,
    'discountPercentage': 7.74,
    'discountedTotal': 73.79,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/sports-accessories/basketball-rim/thumbnail.webp'}],
  'total': 249.95,
  'discountedTotal': 214.68,
  'userId': 15,
  'totalProducts': 3,
  'totalQuantity': 5},
 {'id': 16,
  'products': [{'id': 20,
    'title': 'Cooking Oil',
    'price': 4.99,
    'quantity': 5,
    'total': 24.950000000000003,
    'discountPercentage': 9.33,
    'discountedTotal': 22.62,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/cooking-oil/thumbnail.webp'},
   {'id': 91,
    'title': 'Sports Sneakers Off White & Red',
    'price': 119.99,
    'quantity': 3,
    'total': 359.96999999999997,
    'discountPercentage': 4.97,
    'discountedTotal': 342.08,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/thumbnail.webp'}],
  'total': 384.92,
  'discountedTotal': 364.7,
  'userId': 16,
  'totalProducts': 2,
  'totalQuantity': 8},
 {'id': 17,
  'products': [{'id': 123,
    'title': 'iPhone 13 Pro',
    'price': 1099.99,
    'quantity': 5,
    'total': 5499.95,
    'discountPercentage': 9.37,
    'discountedTotal': 4984.6,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/thumbnail.webp'},
   {'id': 137,
    'title': 'American Football',
    'price': 19.99,
    'quantity': 1,
    'total': 19.99,
    'discountPercentage': 4.93,
    'discountedTotal': 19,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/sports-accessories/american-football/thumbnail.webp'},
   {'id': 25,
    'title': 'Green Bell Pepper',
    'price': 1.29,
    'quantity': 5,
    'total': 6.45,
    'discountPercentage': 0.16,
    'discountedTotal': 6.44,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/thumbnail.webp'},
   {'id': 26,
    'title': 'Green Chili Pepper',
    'price': 0.99,
    'quantity': 5,
    'total': 4.95,

In [29]:
type(cart_data)

list

In [33]:
data_cart = pd.json_normalize(cart_data)
cart_data

[{'id': 1,
  'products': [{'id': 162,
    'title': 'Blue Frock',
    'price': 29.99,
    'quantity': 4,
    'total': 119.96,
    'discountPercentage': 12.13,
    'discountedTotal': 105.41,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/tops/blue-frock/thumbnail.webp'},
   {'id': 113,
    'title': 'Generic Motorcycle',
    'price': 3999.99,
    'quantity': 3,
    'total': 11999.97,
    'discountPercentage': 12.1,
    'discountedTotal': 10547.97,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/motorcycle/generic-motorcycle/thumbnail.webp'},
   {'id': 122,
    'title': 'iPhone 6',
    'price': 299.99,
    'quantity': 3,
    'total': 899.97,
    'discountPercentage': 6.69,
    'discountedTotal': 839.76,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/iphone-6/thumbnail.webp'},
   {'id': 138,
    'title': 'Baseball Ball',
    'price': 8.99,
    'quantity': 2,
    'total': 17.98,
    'discountPercentage': 1.71,
    'discountedTotal': 17.67,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/sports-accessories/baseball-ball/thumbnail.webp'}],
  'total': 13037.88,
  'discountedTotal': 11510.81,
  'userId': 1,
  'totalProducts': 4,
  'totalQuantity': 12},
 {'id': 2,
  'products': [{'id': 86,
    'title': 'Man Short Sleeve Shirt',
    'price': 19.99,
    'quantity': 5,
    'total': 99.94999999999999,
    'discountPercentage': 6.83,
    'discountedTotal': 93.12,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/thumbnail.webp'},
   {'id': 104,
    'title': 'Apple iPhone Charger',
    'price': 19.99,
    'quantity': 2,
    'total': 39.98,
    'discountPercentage': 18.52,
    'discountedTotal': 32.58,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/thumbnail.webp'}],
  'total': 139.93,
  'discountedTotal': 125.7,
  'userId': 2,
  'totalProducts': 2,
  'totalQuantity': 7},
 {'id': 3,
  'products': [{'id': 24,
    'title': 'Fish Steak',
    'price': 14.99,
    'quantity': 1,
    'total': 14.99,
    'discountPercentage': 4.23,
    'discountedTotal': 14.36,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/fish-steak/thumbnail.webp'},
   {'id': 123,
    'title': 'iPhone 13 Pro',
    'price': 1099.99,
    'quantity': 1,
    'total': 1099.99,
    'discountPercentage': 9.37,
    'discountedTotal': 996.92,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/thumbnail.webp'},
   {'id': 129,
    'title': 'Realme X',
    'price': 299.99,
    'quantity': 1,
    'total': 299.99,
    'discountPercentage': 6.95,
    'discountedTotal': 279.14,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/realme-x/thumbnail.webp'},
   {'id': 86,
    'title': 'Man Short Sleeve Shirt',
    'price': 19.99,
    'quantity': 5,
    'total': 99.94999999999999,
    'discountPercentage': 6.83,
    'discountedTotal': 93.12,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/thumbnail.webp'},
   {'id': 8,
    'title': "Dior J'adore",
    'price': 89.99,
    'quantity': 2,
    'total': 179.98,
    'discountPercentage': 14.72,
    'discountedTotal': 153.49,
    'thumbnail': "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"},
   {'id': 157,
    'title': 'Party Glasses',
    'price': 19.99,
    'quantity': 5,
    'total': 99.94999999999999,
    'discountPercentage': 11.22,
    'discountedTotal': 88.74,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/sunglasses/party-glasses/thumbnail.webp'}],
  'total': 1794.85,
  'discountedTotal': 1625.77,
  'userId': 3,
  'totalProducts': 6,
  'totalQuantity': 15},
 {'id': 4,
  'products': [{'id': 92,
    'title': 'Sports Sneakers Off White Red',
    'price': 109.99,
    'quantity': 3,
    'total': 329.96999999999997,
    'discountPercentage': 0.04,
    'discountedTotal': 329.84,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/thumbnail.webp'},
   {'id': 8,
    'title': "Dior J'adore",
    'price': 89.99,
    'quantity': 4,
    'total': 359.96,
    'discountPercentage': 14.72,
    'discountedTotal': 306.97,
    'thumbnail': "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"}],
  'total': 689.93,
  'discountedTotal': 636.81,
  'userId': 4,
  'totalProducts': 2,
  'totalQuantity': 7},
 {'id': 5,
  'products': [{'id': 161,
    'title': 'Samsung Galaxy Tab White',
    'price': 349.99,
    'quantity': 4,
    'total': 1399.96,
    'discountPercentage': 18.2,
    'discountedTotal': 1145.17,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/thumbnail.webp'},
   {'id': 39,
    'title': 'Soft Drinks',
    'price': 1.99,
    'quantity': 4,
    'total': 7.96,
    'discountPercentage': 17.48,
    'discountedTotal': 6.57,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/soft-drinks/thumbnail.webp'},
   {'id': 3,
    'title': 'Powder Canister',
    'price': 14.99,
    'quantity': 4,
    'total': 59.96,
    'discountPercentage': 9.84,
    'discountedTotal': 54.06,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp'}],
  'total': 1467.88,
  'discountedTotal': 1205.8,
  'userId': 5,
  'totalProducts': 3,
  'totalQuantity': 12},
 {'id': 6,
  'products': [{'id': 192,
    'title': 'Rolex Datejust Women',
    'price': 10999.99,
    'quantity': 5,
    'total': 54999.95,
    'discountPercentage': 15.94,
    'discountedTotal': 46232.96,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/womens-watches/rolex-datejust-women/thumbnail.webp'},
   {'id': 130,
    'title': 'Realme XT',
    'price': 349.99,
    'quantity': 1,
    'total': 349.99,
    'discountPercentage': 11.51,
    'discountedTotal': 309.71,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/realme-xt/thumbnail.webp'},
   {'id': 155,
    'title': 'Classic Sun Glasses',
    'price': 24.99,
    'quantity': 4,
    'total': 99.96,
    'discountPercentage': 4.94,
    'discountedTotal': 95.02,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/sunglasses/classic-sun-glasses/thumbnail.webp'},
   {'id': 42,
    'title': 'Water',
    'price': 0.99,
    'quantity': 4,
    'total': 3.96,
    'discountPercentage': 14.92,
    'discountedTotal': 3.37,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/water/thumbnail.webp'}],
  'total': 55453.86,
  'discountedTotal': 46641.06,
  'userId': 6,
  'totalProducts': 4,
  'totalQuantity': 14},
 {'id': 7,
  'products': [{'id': 56,
    'title': 'Electric Stove',
    'price': 49.99,
    'quantity': 1,
    'total': 49.99,
    'discountPercentage': 14.04,
    'discountedTotal': 42.97,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/electric-stove/thumbnail.webp'},
   {'id': 136,
    'title': 'Vivo X21',
    'price': 499.99,
    'quantity': 1,
    'total': 499.99,
    'discountPercentage': 17.41,
    'discountedTotal': 412.94,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/vivo-x21/thumbnail.webp'},
   {'id': 9,
    'title': 'Dolce Shine Eau de',
    'price': 69.99,
    'quantity': 2,
    'total': 139.98,
    'discountPercentage': 0.62,
    'discountedTotal': 139.11,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp'},
   {'id': 120,
    'title': 'Vaseline Men Body and Face Lotion',
    'price': 9.99,
    'quantity': 4,
    'total': 39.96,
    'discountPercentage': 13.39,
    'discountedTotal': 34.61,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/skin-care/vaseline-men-body-and-face-lotion/thumbnail.webp'},
   {'id': 56,
    'title': 'Electric Stove',
    'price': 49.99,
    'quantity': 1,
    'total': 49.99,
    'discountPercentage': 14.04,
    'discountedTotal': 42.97,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/electric-stove/thumbnail.webp'},
   {'id': 90,
    'title': 'Puma Future Rider Trainers',
    'price': 89.99,
    'quantity': 5,
    'total': 449.95,
    'discountPercentage': 4.2,
    'discountedTotal': 431.05,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/thumbnail.webp'}],
  'total': 1229.86,
  'discountedTotal': 1103.65,
  'userId': 7,
  'totalProducts': 6,
  'totalQuantity': 14},
 {'id': 8,
  'products': [{'id': 18,
    'title': 'Cat Food',
    'price': 8.99,
    'quantity': 2,
    'total': 17.98,
    'discountPercentage': 9.58,
    'discountedTotal': 16.26,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/cat-food/thumbnail.webp'},
   {'id': 50,
    'title': 'Black Whisk',
    'price': 9.99,
    'quantity': 3,
    'total': 29.97,
    'discountPercentage': 10.24,
    'discountedTotal': 26.9,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/black-whisk/thumbnail.webp'},
   {'id': 162,
    'title': 'Blue Frock',
    'price': 29.99,
    'quantity': 4,
    'total': 119.96,
    'discountPercentage': 12.13,
    'discountedTotal': 105.41,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/tops/blue-frock/thumbnail.webp'},
   {'id': 11,
    'title': 'Annibale Colombo Bed',
    'price': 1899.99,
    'quantity': 3,
    'total': 5699.97,
    'discountPercentage': 8.57,
    'discountedTotal': 5211.48,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp'},
   {'id': 108,
    'title': 'iPhone 12 Silicone Case with MagSafe Plum',
    'price': 29.99,
    'quantity': 4,
    'total': 119.96,
    'discountPercentage': 13.85,
    'discountedTotal': 103.35,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/thumbnail.webp'},
   {'id': 106,
    'title': 'Apple Watch Series 4 Gold',
    'price': 349.99,
    'quantity': 1,
    'total': 349.99,
    'discountPercentage': 12.02,
    'discountedTotal': 307.92,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-watch-series-4-gold/thumbnail.webp'}],
  'total': 6337.83,
  'discountedTotal': 5771.32,
  'userId': 8,
  'totalProducts': 6,
  'totalQuantity': 17},
 {'id': 9,
  'products': [{'id': 1,
    'title': 'Essence Mascara Lash Princess',
    'price': 9.99,
    'quantity': 3,
    'total': 29.97,
    'discountPercentage': 10.48,
    'discountedTotal': 26.83,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp'},
   {'id': 98,
    'title': 'Rolex Submariner Watch',
    'price': 13999.99,
    'quantity': 2,
    'total': 27999.98,
    'discountPercentage': 5.05,
    'discountedTotal': 26585.98,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-watches/rolex-submariner-watch/thumbnail.webp'},
   {'id': 132,
    'title': 'Samsung Galaxy S8',
    'price': 499.99,
    'quantity': 3,
    'total': 1499.97,
    'discountPercentage': 19.45,
    'discountedTotal': 1208.23,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s8/thumbnail.webp'},
   {'id': 90,
    'title': 'Puma Future Rider Trainers',
    'price': 89.99,
    'quantity': 2,
    'total': 179.98,
    'discountPercentage': 4.2,
    'discountedTotal': 172.42,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/thumbnail.webp'}],
  'total': 29709.9,
  'discountedTotal': 27993.46,
  'userId': 9,
  'totalProducts': 4,
  'totalQuantity': 10},
 {'id': 10,
  'products': [{'id': 41,
    'title': 'Tissue Paper Box',
    'price': 2.49,
    'quantity': 1,
    'total': 2.49,
    'discountPercentage': 13.28,
    'discountedTotal': 2.16,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/tissue-paper-box/thumbnail.webp'},
   {'id': 108,
    'title': 'iPhone 12 Silicone Case with MagSafe Plum',
    'price': 29.99,
    'quantity': 5,
    'total': 149.95,
    'discountPercentage': 13.85,
    'discountedTotal': 129.18,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/thumbnail.webp'}],
  'total': 152.44,
  'discountedTotal': 131.34,
  'userId': 10,
  'totalProducts': 2,
  'totalQuantity': 6},
 {'id': 11,
  'products': [{'id': 115,
    'title': 'MotoGP CI.H1',
    'price': 14999.99,
    'quantity': 4,
    'total': 59999.96,
    'discountPercentage': 6.92,
    'discountedTotal': 55847.96,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/motorcycle/motogp-ci.h1/thumbnail.webp'},
   {'id': 101,
    'title': 'Apple AirPods Max Silver',
    'price': 549.99,
    'quantity': 2,
    'total': 1099.98,
    'discountPercentage': 13.67,
    'discountedTotal': 949.61,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/thumbnail.webp'},
   {'id': 55,
    'title': 'Egg Slicer',
    'price': 6.99,
    'quantity': 4,
    'total': 27.96,
    'discountPercentage': 14.76,
    'discountedTotal': 23.83,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/egg-slicer/thumbnail.webp'},
   {'id': 25,
    'title': 'Green Bell Pepper',
    'price': 1.29,
    'quantity': 3,
    'total': 3.87,
    'discountPercentage': 0.16,
    'discountedTotal': 3.86,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/thumbnail.webp'},
   {'id': 161,
    'title': 'Samsung Galaxy Tab White',
    'price': 349.99,
    'quantity': 2,
    'total': 699.98,
    'discountPercentage': 18.2,
    'discountedTotal': 572.58,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/thumbnail.webp'}],
  'total': 61831.75,
  'discountedTotal': 57397.84,
  'userId': 11,
  'totalProducts': 5,
  'totalQuantity': 15},
 {'id': 12,
  'products': [{'id': 117,
    'title': 'Sportbike Motorcycle',
    'price': 7499.99,
    'quantity': 1,
    'total': 7499.99,
    'discountPercentage': 11.58,
    'discountedTotal': 6631.49,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/motorcycle/sportbike-motorcycle/thumbnail.webp'},
   {'id': 28,
    'title': 'Ice Cream',
    'price': 5.49,
    'quantity': 5,
    'total': 27.450000000000003,
    'discountPercentage': 8.69,
    'discountedTotal': 25.06,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/ice-cream/thumbnail.webp'},
   {'id': 98,
    'title': 'Rolex Submariner Watch',
    'price': 13999.99,
    'quantity': 2,
    'total': 27999.98,
    'discountPercentage': 5.05,
    'discountedTotal': 26585.98,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-watches/rolex-submariner-watch/thumbnail.webp'},
   {'id': 8,
    'title': "Dior J'adore",
    'price': 89.99,
    'quantity': 1,
    'total': 89.99,
    'discountPercentage': 14.72,
    'discountedTotal': 76.74,
    'thumbnail': "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"},
   {'id': 162,
    'title': 'Blue Frock',
    'price': 29.99,
    'quantity': 5,
    'total': 149.95,
    'discountPercentage': 12.13,
    'discountedTotal': 131.76,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/tops/blue-frock/thumbnail.webp'},
   {'id': 14,
    'title': 'Knoll Saarinen Executive Conference Chair',
    'price': 499.99,
    'quantity': 4,
    'total': 1999.96,
    'discountPercentage': 2.01,
    'discountedTotal': 1959.76,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/thumbnail.webp'}],
  'total': 37767.32,
  'discountedTotal': 35410.79,
  'userId': 12,
  'totalProducts': 6,
  'totalQuantity': 18},
 {'id': 13,
  'products': [{'id': 35,
    'title': 'Potatoes',
    'price': 2.29,
    'quantity': 2,
    'total': 4.58,
    'discountPercentage': 5.38,
    'discountedTotal': 4.33,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/potatoes/thumbnail.webp'},
   {'id': 23,
    'title': 'Eggs',
    'price': 2.99,
    'quantity': 4,
    'total': 11.96,
    'discountPercentage': 11.05,
    'discountedTotal': 10.64,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/eggs/thumbnail.webp'}],
  'total': 16.54,
  'discountedTotal': 14.97,
  'userId': 13,
  'totalProducts': 2,
  'totalQuantity': 6},
 {'id': 14,
  'products': [{'id': 44,
    'title': 'Family Tree Photo Frame',
    'price': 29.99,
    'quantity': 4,
    'total': 119.96,
    'discountPercentage': 14.87,
    'discountedTotal': 102.12,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/home-decoration/family-tree-photo-frame/thumbnail.webp'},
   {'id': 68,
    'title': 'Pan',
    'price': 24.99,
    'quantity': 1,
    'total': 24.99,
    'discountPercentage': 3,
    'discountedTotal': 24.24,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/pan/thumbnail.webp'},
   {'id': 65,
    'title': 'Lunch Box',
    'price': 12.99,
    'quantity': 5,
    'total': 64.95,
    'discountPercentage': 10.34,
    'discountedTotal': 58.23,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/lunch-box/thumbnail.webp'}],
  'total': 209.9,
  'discountedTotal': 184.59,
  'userId': 14,
  'totalProducts': 3,
  'totalQuantity': 10},
 {'id': 15,
  'products': [{'id': 61,
    'title': 'Hand Blender',
    'price': 34.99,
    'quantity': 2,
    'total': 69.98,
    'discountPercentage': 17.02,
    'discountedTotal': 58.07,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/hand-blender/thumbnail.webp'},
   {'id': 105,
    'title': 'Apple MagSafe Battery Pack',
    'price': 99.99,
    'quantity': 1,
    'total': 99.99,
    'discountPercentage': 17.17,
    'discountedTotal': 82.82,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/thumbnail.webp'},
   {'id': 141,
    'title': 'Basketball Rim',
    'price': 39.99,
    'quantity': 2,
    'total': 79.98,
    'discountPercentage': 7.74,
    'discountedTotal': 73.79,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/sports-accessories/basketball-rim/thumbnail.webp'}],
  'total': 249.95,
  'discountedTotal': 214.68,
  'userId': 15,
  'totalProducts': 3,
  'totalQuantity': 5},
 {'id': 16,
  'products': [{'id': 20,
    'title': 'Cooking Oil',
    'price': 4.99,
    'quantity': 5,
    'total': 24.950000000000003,
    'discountPercentage': 9.33,
    'discountedTotal': 22.62,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/cooking-oil/thumbnail.webp'},
   {'id': 91,
    'title': 'Sports Sneakers Off White & Red',
    'price': 119.99,
    'quantity': 3,
    'total': 359.96999999999997,
    'discountPercentage': 4.97,
    'discountedTotal': 342.08,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/thumbnail.webp'}],
  'total': 384.92,
  'discountedTotal': 364.7,
  'userId': 16,
  'totalProducts': 2,
  'totalQuantity': 8},
 {'id': 17,
  'products': [{'id': 123,
    'title': 'iPhone 13 Pro',
    'price': 1099.99,
    'quantity': 5,
    'total': 5499.95,
    'discountPercentage': 9.37,
    'discountedTotal': 4984.6,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/thumbnail.webp'},
   {'id': 137,
    'title': 'American Football',
    'price': 19.99,
    'quantity': 1,
    'total': 19.99,
    'discountPercentage': 4.93,
    'discountedTotal': 19,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/sports-accessories/american-football/thumbnail.webp'},
   {'id': 25,
    'title': 'Green Bell Pepper',
    'price': 1.29,
    'quantity': 5,
    'total': 6.45,
    'discountPercentage': 0.16,
    'discountedTotal': 6.44,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/thumbnail.webp'},
   {'id': 26,
    'title': 'Green Chili Pepper',
    'price': 0.99,
    'quantity': 5,
    'total': 4.95,

In [34]:
df = pd.DataFrame(cart_data)
df

,id,products,total,discountedTotal,userId,totalProducts,totalQuantity
0,1,"[{'id': 162, 'title': 'Blue Frock', 'price': 2...",13037.88,11510.81,1,4,12
1,2,"[{'id': 86, 'title': 'Man Short Sleeve Shirt',...",139.93,125.70,2,2,7
2,3,"[{'id': 24, 'title': 'Fish Steak', 'price': 14...",1794.85,1625.77,3,6,15
3,4,"[{'id': 92, 'title': 'Sports Sneakers Off Whit...",689.93,636.81,4,2,7
4,5,"[{'id': 161, 'title': 'Samsung Galaxy Tab Whit...",1467.88,1205.80,5,3,12
5,6,"[{'id': 192, 'title': 'Rolex Datejust Women', ...",55453.86,46641.06,6,4,14
6,7,"[{'id': 56, 'title': 'Electric Stove', 'price'...",1229.86,1103.65,7,6,14
7,8,"[{'id': 18, 'title': 'Cat Food', 'price': 8.99...",6337.83,5771.32,8,6,17
8,9,"[{'id': 1, 'title': 'Essence Mascara Lash Prin...",29709.90,27993.46,9,4,10
9,10,"[{'id': 41, 'title': 'Tissue Paper Box', 'pric...",152.44,131.34,10,2,6
10,11,"[{'id': 115, 'title': 'MotoGP CI.H1', 'price':...",61831.75,57397.84,11,5,15
11,12,"[{'id': 117, 'title': 'Sportbike Motorcycle', ...",37767.32,35410.79,12,6,18
12,13,"[{'id': 35, 'title': 'Potatoes', 'price': 2.29...",16.54,14.97,13,2,6
13,14,"[{'id': 44, 'title': 'Family Tree Photo Frame'...",209.90,184.59,14,3,10
14,15,"[{'id': 61, 'title': 'Hand Blender', 'price': ...",249.95,214.68,15,3,5
15,16,"[{'id': 20, 'title': 'Cooking Oil', 'price': 4...",384.92,364.70,16,2,8
16,17,"[{'id': 123, 'title': 'iPhone 13 Pro', 'price'...",5531.34,5014.94,17,4,16
17,18,"[{'id': 169, 'title': 'Dodge Hornet GT Plus', ...",128999.90,124978.81,18,2,10
18,19,"[{'id': 22, 'title': 'Dog Food', 'price': 10.9...",22142.88,21308.13,19,5,12
19,20,"[{'id': 123, 'title': 'iPhone 13 Pro', 'price'...",4711.88,4251.41,20,4,12
20,21,"[{'id': 79, 'title': 'Asus Zenbook Pro Dual Sc...",12939.94,10966.03,21,3,6
21,22,"[{'id': 16, 'title': 'Apple', 'price': 1.99, '...",307.92,296.47,22,3,8
22,23,"[{'id': 127, 'title': 'Oppo K1', 'price': 299....",2499.91,2123.87,23,2,9
23,24,"[{'id': 117, 'title': 'Sportbike Motorcycle', ...",30299.94,26780.04,24,2,6
24,25,"[{'id': 32, 'title': 'Milk', 'price': 3.49, 'q...",1228.35,1070.83,25,5,15
25,26,"[{'id': 122, 'title': 'iPhone 6', 'price': 299...",1111.84,1021.64,26,4,16
26,27,"[{'id': 192, 'title': 'Rolex Datejust Women', ...",111014.85,100496.36,27,4,15
27,28,"[{'id': 182, 'title': 'Green Crystal Earring',...",5944.77,5531.37,28,6,23
28,29,"[{'id': 174, 'title': 'Prada Women Bag', 'pric...",2359.84,2077.88,29,4,16
29,30,"[{'id': 143, 'title': 'Cricket Bat', 'price': ...",186110.85,155507.16,30,6,15

In [35]:
final_df = pd.json_normalize(
    cart_data, 
    record_path=['products'], 
    meta=['id', 'total', 'discountedTotal', 'userId', 'totalProducts', 'totalQuantity'],
    meta_prefix='cart_',
    record_prefix='product_'
)

final_df.head()

,product_id,product_title,product_price,product_quantity,product_total,product_discountPercentage,product_discountedTotal,product_thumbnail,cart_id,cart_total,cart_discountedTotal,cart_userId,cart_totalProducts,cart_totalQuantity
0,162,Blue Frock,29.99,4,119.96,12.13,105.41,https://cdn.dummyjson.com/product-images/tops/...,1,13037.88,11510.81,1,4,12
1,113,Generic Motorcycle,3999.99,3,11999.97,12.10,10547.97,https://cdn.dummyjson.com/product-images/motor...,1,13037.88,11510.81,1,4,12
2,122,iPhone 6,299.99,3,899.97,6.69,839.76,https://cdn.dummyjson.com/product-images/smart...,1,13037.88,11510.81,1,4,12
3,138,Baseball Ball,8.99,2,17.98,1.71,17.67,https://cdn.dummyjson.com/product-images/sport...,1,13037.88,11510.81,1,4,12
4,86,Man Short Sleeve Shirt,19.99,5,99.95,6.83,93.12,https://cdn.dummyjson.com/product-images/mens-...,2,139.93,125.7,2,2,7

In [36]:
df_product = pd.DataFrame(final_df)
df_product

,product_id,product_title,product_price,product_quantity,product_total,product_discountPercentage,product_discountedTotal,product_thumbnail,cart_id,cart_total,cart_discountedTotal,cart_userId,cart_totalProducts,cart_totalQuantity
0,162,Blue Frock,29.99,4,119.96,12.13,105.41,https://cdn.dummyjson.com/product-images/tops/...,1,13037.88,11510.81,1,4,12
1,113,Generic Motorcycle,3999.99,3,11999.97,12.10,10547.97,https://cdn.dummyjson.com/product-images/motor...,1,13037.88,11510.81,1,4,12
2,122,iPhone 6,299.99,3,899.97,6.69,839.76,https://cdn.dummyjson.com/product-images/smart...,1,13037.88,11510.81,1,4,12
3,138,Baseball Ball,8.99,2,17.98,1.71,17.67,https://cdn.dummyjson.com/product-images/sport...,1,13037.88,11510.81,1,4,12
4,86,Man Short Sleeve Shirt,19.99,5,99.95,6.83,93.12,https://cdn.dummyjson.com/product-images/mens-...,2,139.93,125.7,2,2,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,135,Vivo V9,299.99,2,599.98,17.67,493.96,https://cdn.dummyjson.com/product-images/smart...,30,186110.85,155507.16,30,6,15
110,126,Oppo F19 Pro Plus,399.99,1,399.99,18.64,325.43,https://cdn.dummyjson.com/product-images/smart...,30,186110.85,155507.16,30,6,15
111,77,Yellow Peeler,5.99,1,5.99,12.48,5.24,https://cdn.dummyjson.com/product-images/kitch...,30,186110.85,155507.16,30,6,15
112,3,Powder Canister,14.99,5,74.95,9.84,67.57,https://cdn.dummyjson.com/product-images/beaut...,30,186110.85,155507.16,30,6,15
113,170,Durango SXT RWD,36999.99,5,184999.95,16.44,154585.96,https://cdn.dummyjson.com/product-images/vehic...,30,186110.85,155507.16,30,6,15

In [41]:
final_df.to_csv("final_cart_data.csv", index=False)

In [42]:
# Save the data directly as a modern Excel Workbook
final_df.to_excel("cart_data_final.xlsx", index=False)